# Generated by Django 4.2.7 on 2024-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='platform',
            field=models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('google', 'Google')], default='zomato', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='restaurant_branch',
            field=models.CharField(choices=[('ANDHERI', 'ANDHERI'), ('MALAD', 'MALAD'), ('BORIVALI', 'BORIVALI')], default='Andheri', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
